# Generated by Django 6.0.5 on 2026-05-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('delayed', 'Delayed'), ('completed', 'Completed')], max_length=20)),
                ('client', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('project_type', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('infrastructure', 'Infrastructure'), ('industrial', 'Industrial')], max_length=30)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('budget', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('delayed_issues', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('title', models.CharField(choices=[('project manager', 'Project Manager'), ('contractor', 'Contractor'), ('supervisor', 'supervisor'), ('site engineer', 'Site Engineer')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('difficulty', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=40)),
                ('status', models.CharField(choices=[('completed', 'Complete'), ('pending', 'Pending'), ('in progress', 'In Progress'), ('blocked', 'Blocked'), ('under review', 'Under Review')], default='pending', max_length=30)),
                ('due_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='buildmaster.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='buildmaster.teammember'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='projects', to='buildmaster.teammember'),
        ),
    ]
