# Generated by Django 6.0.5 on 2026-05-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildmaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='status',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(choices=[('project manager', 'Project Manager'), ('contractor', 'Contractor'), ('supervisor', 'Supervisor'), ('site engineer', 'Site Engineer')], max_length=30),
        ),
    ]
