# Generated by Django 6.0.5 on 2026-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildmaster', '0002_remove_teammember_status_alter_teammember_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
